### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_cdl#1]
Hola,

He revisado el README:

- La propuesta es adecuada. Adelante.
- En la lista de participantes usad el formato lista de Markdown. Debéis dejar un espacio entre el guión y el texto.
- Podéis enlazar cada participante a su página web de GitHub.

**Comment by manusandin** [comment]
Hola @oscarperpinan , 
Ya hemos cambiado todo lo que nos habías comentado.
Nos ponemos con el trabajo.

**Comment by oscarperpinan** [comment]
Bien. Cerrad el issue entonces.
