### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto_cdl#3]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by manusandin** [comment]
Hola, @oscarperpinan. Subimos ya tanto el diagrama de flujo como el menú principal. Creemos que ambos están bien, pero si vieses algo que mejorar háznoslo saber. Gracias!!

**Comment by orgynmobs** [comment]
Habéis subido los ficheros pero os falta cerrar la issue. Podéis hacerlo justo aquí abajo. Cuando lleguéis al 100% de la milestone, cerradla también
